# Generated by Django 6.0.5 on 2026-06-02 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('migration', '0003_invoice_zoho_id_invoice_zoho_migrated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='zoho_access_token',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appuser',
            name='zoho_client_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='appuser',
            name='zoho_client_secret',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='appuser',
            name='zoho_organization_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='appuser',
            name='zoho_refresh_token',
            field=models.TextField(blank=True, null=True),
        ),
    ]
