# Generated by Django 6.0.5 on 2026-06-03 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('migration', '0004_appuser_zoho_access_token_appuser_zoho_client_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(max_length=255, unique=True)),
                ('account_code', models.CharField(blank=True, default='', max_length=255)),
                ('account_type', models.CharField(blank=True, max_length=100, null=True)),
                ('zoho_id', models.CharField(blank=True, max_length=100, null=True)),
                ('zoho_migrated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('rate', models.CharField(default='0', max_length=50)),
                ('description', models.TextField(blank=True, default='')),
                ('sku', models.CharField(blank=True, default='', max_length=255)),
                ('product_type', models.CharField(blank=True, default='', max_length=255)),
                ('gst_applicable', models.CharField(blank=True, default='', max_length=100)),
                ('gst_rate', models.CharField(blank=True, default='0', max_length=50)),
                ('hsn_code', models.CharField(blank=True, default='', max_length=100)),
                ('zoho_id', models.CharField(blank=True, max_length=100, null=True)),
                ('zoho_migrated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='appuser',
            name='zoho_refresh_token',
        ),
    ]

