# Generated by Django 6.0.5 on 2026-06-03 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('migration', '0005_account_item_remove_appuser_zoho_refresh_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='zoho_refresh_token',
            field=models.TextField(blank=True, null=True),
        ),
    ]
