# Generated by Django 6.0.5 on 2026-06-04 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('migration', '0007_alter_appuser_zoho_organization_id_tax'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('email', models.CharField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('address', models.CharField(blank=True, max_length=500, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('pincode', models.CharField(blank=True, max_length=20, null=True)),
                ('country', models.CharField(blank=True, default='India', max_length=100, null=True)),
                ('zoho_id', models.CharField(blank=True, max_length=100, null=True)),
                ('zoho_migrated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'migration_customer',
            },
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('email', models.CharField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('address', models.CharField(blank=True, max_length=500, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('pincode', models.CharField(blank=True, max_length=20, null=True)),
                ('country', models.CharField(blank=True, default='India', max_length=100, null=True)),
                ('zoho_id', models.CharField(blank=True, max_length=100, null=True)),
                ('zoho_migrated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'migration_vendor',
            },
        ),
    ]
