# Generated by Django 6.0.5 on 2026-06-04 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('migration', '0008_customer_vendor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tax',
            name='parent',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
