# Generated by Django 6.0.5 on 2026-06-04 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('migration', '0009_alter_tax_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='tax',
            name='zoho_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterModelTable(
            name='tax',
            table='migration_tax',
        ),
    ]
