# Generated by Django 6.0.5 on 2026-06-05 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('migration', '0010_tax_zoho_id_alter_tax_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=255)),
                ('credit_note_number', models.CharField(max_length=100, unique=True)),
                ('credit_note_date', models.DateField(blank=True, null=True)),
                ('amount', models.CharField(default='0', max_length=50)),
                ('zoho_id', models.CharField(blank=True, max_length=100, null=True)),
                ('zoho_migrated_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voucher_number', models.CharField(max_length=100, unique=True)),
                ('voucher_date', models.DateField(blank=True, null=True)),
                ('narration', models.TextField(blank=True)),
                ('amount', models.CharField(default='0', max_length=50)),
                ('zoho_id', models.CharField(blank=True, max_length=100, null=True)),
                ('zoho_migrated_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_name', models.CharField(max_length=255)),
                ('payment_number', models.CharField(max_length=100, unique=True)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('amount', models.CharField(default='0', max_length=50)),
                ('payment_mode', models.CharField(blank=True, max_length=100)),
                ('zoho_id', models.CharField(blank=True, max_length=100, null=True)),
                ('zoho_migrated_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_name', models.CharField(max_length=255)),
                ('bill_number', models.CharField(max_length=100, unique=True)),
                ('bill_date', models.DateField(blank=True, null=True)),
                ('amount', models.CharField(default='0', max_length=50)),
                ('zoho_id', models.CharField(blank=True, max_length=100, null=True)),
                ('zoho_migrated_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='VendorCredit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_name', models.CharField(max_length=255)),
                ('vendor_credit_number', models.CharField(max_length=100, unique=True)),
                ('vendor_credit_date', models.DateField(blank=True, null=True)),
                ('amount', models.CharField(default='0', max_length=50)),
                ('zoho_id', models.CharField(blank=True, max_length=100, null=True)),
                ('zoho_migrated_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
