# Generated by Django 6.0.5 on 2026-06-06 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('migration', '0011_creditnote_journal_payment_purchase_vendorcredit'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpeningBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ledger_name', models.CharField(max_length=255, unique=True)),
                ('parent', models.CharField(blank=True, max_length=255, null=True)),
                ('opening_balance', models.FloatField(default=0.0)),
                ('balance_type', models.CharField(default='debit', max_length=10)),
                ('zoho_account_id', models.CharField(blank=True, max_length=100, null=True)),
                ('is_pushed', models.BooleanField(default=False)),
                ('synced_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'migration_openingbalance',
            },
        ),
    ]
