# Generated by Django 6.0.5 on 2026-06-08 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('migration', '0012_openingbalance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_number', models.CharField(max_length=100, unique=True)),
                ('expense_date', models.DateField(blank=True, null=True)),
                ('account_name', models.CharField(blank=True, max_length=255)),
                ('paid_through', models.CharField(blank=True, max_length=255)),
                ('amount', models.CharField(default='0', max_length=50)),
                ('narration', models.TextField(blank=True)),
                ('zoho_id', models.CharField(blank=True, max_length=100, null=True)),
                ('zoho_migrated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'migration_expense',
            },
        ),
    ]
