# Generated by Django 6.0.5 on 2026-06-08 07:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('migration', '0013_expense'),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(max_length=255)),
                ('debit', models.CharField(default='0.00', max_length=50)),
                ('credit', models.CharField(default='0.00', max_length=50)),
                ('journal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='migration.journal')),
            ],
            options={
                'db_table': 'migration_journalline',
            },
        ),
    ]
