# Generated by Django 6.0.5 on 2026-06-08 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('migration', '0014_journalline'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='agst_ref_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
