# Generated by Django 6.0.5 on 2026-06-08 07:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('migration', '0015_receipt_agst_ref_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=255)),
                ('quantity_raw', models.CharField(default='1', max_length=100)),
                ('qty_value', models.DecimalField(decimal_places=4, default=1, max_digits=14)),
                ('qty_unit', models.CharField(default='Nos', max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('rate', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='migration.purchase')),
            ],
            options={
                'db_table': 'migration_purchaselineitem',
            },
        ),
    ]
