# Generated by Django 6.0.5 on 2026-06-09 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('migration', '0018_customer_created_at_vendor_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='expense_date',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='expense_number',
        ),
        migrations.AddField(
            model_name='expense',
            name='payment_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='payment_number',
            field=models.CharField(default='exit', max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='expense',
            name='account_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='expense',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='expense',
            name='paid_through',
            field=models.CharField(default='Cash', max_length=255),
        ),
    ]
