# Generated by Django 6.0.5 on 2026-06-10 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('migration', '0019_remove_expense_expense_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaselineitem',
            name='qty_unit',
        ),
        migrations.RemoveField(
            model_name='purchaselineitem',
            name='qty_value',
        ),
        migrations.RemoveField(
            model_name='purchaselineitem',
            name='quantity_raw',
        ),
        migrations.RemoveField(
            model_name='receipt',
            name='agst_ref_name',
        ),
        migrations.AddField(
            model_name='purchaselineitem',
            name='quantity',
            field=models.CharField(default='1', max_length=100),
        ),
        migrations.AddField(
            model_name='tax',
            name='zoho_migrated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='journalline',
            name='credit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AlterField(
            model_name='journalline',
            name='debit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AlterModelTable(
            name='journalline',
            table=None,
        ),
        migrations.AlterModelTable(
            name='purchaselineitem',
            table=None,
        ),
    ]
