# Generated by Django 6.0.5 on 2026-06-10 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('migration', '0020_remove_purchaselineitem_qty_unit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoicelineitem',
            name='quantity_raw',
        ),
    ]
