# Generated by Django 6.0.5 on 2026-06-11 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('migration', '0021_remove_quantity_raw'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditnote',
            name='cgst',
            field=models.CharField(default='0', max_length=50),
        ),
        migrations.AddField(
            model_name='creditnote',
            name='igst',
            field=models.CharField(default='0', max_length=50),
        ),
        migrations.AddField(
            model_name='creditnote',
            name='sgst',
            field=models.CharField(default='0', max_length=50),
        ),
        migrations.AddField(
            model_name='creditnote',
            name='total_amount',
            field=models.CharField(default='0', max_length=50),
        ),
        migrations.AddField(
            model_name='purchase',
            name='cgst',
            field=models.CharField(default='0', max_length=50),
        ),
        migrations.AddField(
            model_name='purchase',
            name='igst',
            field=models.CharField(default='0', max_length=50),
        ),
        migrations.AddField(
            model_name='purchase',
            name='sgst',
            field=models.CharField(default='0', max_length=50),
        ),
        migrations.AddField(
            model_name='purchase',
            name='total_amount',
            field=models.CharField(default='0', max_length=50),
        ),
    ]
