# Generated by Django 6.0.5 on 2026-06-15 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('migration', '0024_remove_item_supply_type_raw'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='type_of_supply',
            field=models.CharField(blank=True, choices=[('Goods', 'Goods'), ('Services', 'Services'), ('Goods & Services', 'Goods & Services'), ('Unknown', 'Unknown')], help_text='Type of Supply for GST', max_length=50, null=True),
        ),
    ]
