# Generated by Django 6.0.5 on 2026-06-15 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('migration', '0025_payment_transaction_kind_receipt_transaction_kind_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditnote',
            name='invoice_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
