# Generated by Django 6.0.5 on 2026-06-22 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('migration', '0025_alter_item_type_of_supply'),
        ('migration', '0026_creditnote_invoice_number'),
    ]

    operations = [
    ]
