# Generated by Django 6.0.5 on 2026-06-22 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('migration', '0026_creditnote_invoice_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='zohoconfig',
            name='region',
            field=models.CharField(choices=[('com', 'Global (.com)'), ('in', 'India (.in)'), ('eu', 'Europe (.eu)'), ('com.au', 'Australia (.com.au)'), ('jp', 'Japan (.jp)'), ('com.cn', 'China (.com.cn)'), ('sa', 'Saudi Arabia (.sa)'), ('ca', 'Canada (.ca)')], default='com', max_length=10),
        ),
    ]
