# Generated by Django 6.0.5 on 2026-06-22 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('migration', '0027_merge_20260622_1440'),
    ]

    operations = [
        migrations.AddField(
            model_name='zohoconfig',
            name='api_base_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
