# Generated by Django 6.0.5 on 2026-06-23 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('migration', '0027_zohoconfig_region'),
        ('migration', '0028_zohoconfig_api_base_url'),
    ]

    operations = [
    ]
