# Generated by Django 6.0.5 on 2026-06-23 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('migration', '0029_merge_20260623_1040'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zohoconfig',
            name='region',
        ),
    ]
